# PyTorch 学习-01
> 主要学习torch类型的基本操作

In [2]:
import torch

使用`c++
__version__`
可以查看torch的版本

In [3]:
print(torch.__version__)

1.3.1


## Tensor
Tensor 张量异常重要！他的维度和各种转换一定要会
下面可以建立一个空的
初始化一个5*3的tensor,但是注意里面的值不完全是0

In [12]:
x=torch.empty(5,3)
print(type(x))#输出格式
print(x.shape)
print(x.size())#上面两个都能输出尺寸
print(x)

<class 'torch.Tensor'>
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


- 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

也可以创建一个随机的tensor

In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.6397, 0.7973, 0.2733],
        [0.4129, 0.9494, 0.9040],
        [0.5542, 0.5121, 0.7883],
        [0.3696, 0.5401, 0.5085],
        [0.2934, 0.8160, 0.5807]])


创建5*3long型全零tensor

In [16]:
x=torch.zeros(5,3,dtype=torch.long)#这里tensor数据类型的long注意
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


也可以自定创建数据

In [17]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型。

In [19]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0169,  0.9148, -1.3145],
        [-0.5552, -1.7487,  0.7503],
        [-0.2536, -0.3840,  0.0460],
        [-0.0587,  0.7960, -0.3910],
        [ 1.7057,  0.8117, -1.4618]])


## Tensor操作
### 加法


In [20]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


In [21]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


In [22]:
y.add_(x)
print(y)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


## 索引

我们还可以使用类似NumPy的索引操作来访问Tensor的一部分,
需要注意的是:**索引出来的结果与原数据共享内存,也即修改一个,另一个会跟着修改.**

In [28]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(x)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [29]:
y=x[0,:] #取第一维
print(y)

tensor([1, 2, 3])


In [33]:
y+=1
print(y) #y是x的索引出来的向量
print(x[0,:])

tensor([5, 6, 7])
tensor([5, 6, 7])


In [34]:
# 原来x的维度是5*3
y=x.view(15)
z=x.view(-1,5)  #-1所指的维度可以根据其他维度的值推出来。例如指定第二维是5，那么计算得到第一维是3
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)**

In [35]:
x+=1
print(x)
print(y)

tensor([[ 6,  7,  8],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13],
        [14, 15, 16]])
tensor([ 6,  7,  8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


> 这里非常重要！经常会使用

所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是**其拷贝**，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。

In [36]:
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[ 5,  6,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([ 6,  7,  8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


> 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

item()函数可以将tensor里面的数拿出来

In [37]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.2080])
-0.20800696313381195
