# PyTorch 学习-01
> 主要学习torch类型的基本操作

In [2]:
import torch

使用`
__version__
`
可以查看torch的版本

In [4]:
print(torch.__version__)

1.10.0


## Tensor
Tensor 张量异常重要！他的维度和各种转换一定要会
下面可以建立一个空的
初始化一个5*3的tensor,但是注意里面的值不完全是0

In [12]:
x=torch.empty(5,3)
print(type(x))#输出格式
print(x.shape)
print(x.size())#上面两个都能输出尺寸
print(x)

<class 'torch.Tensor'>
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


- 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

也可以创建一个随机的tensor

In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.6397, 0.7973, 0.2733],
        [0.4129, 0.9494, 0.9040],
        [0.5542, 0.5121, 0.7883],
        [0.3696, 0.5401, 0.5085],
        [0.2934, 0.8160, 0.5807]])


创建5*3long型全零tensor

In [16]:
x=torch.zeros(5,3,dtype=torch.long)#这里tensor数据类型的long注意
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


也可以自定创建数据

In [17]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型。

In [19]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0169,  0.9148, -1.3145],
        [-0.5552, -1.7487,  0.7503],
        [-0.2536, -0.3840,  0.0460],
        [-0.0587,  0.7960, -0.3910],
        [ 1.7057,  0.8117, -1.4618]])


## Tensor操作
### 加法


In [20]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


In [21]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


In [22]:
y.add_(x)
print(y)

tensor([[ 1.1508,  1.0725, -1.0880],
        [-0.3367, -0.8888,  0.8350],
        [ 0.4997,  0.5211,  0.2321],
        [ 0.5887,  0.8018, -0.1726],
        [ 1.8204,  1.2431, -0.7298]])


## 索引

我们还可以使用类似NumPy的索引操作来访问Tensor的一部分,
需要注意的是:**索引出来的结果与原数据共享内存,也即修改一个,另一个会跟着修改.**

In [28]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(x)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [29]:
y=x[0,:] #取第一维
print(y)

tensor([1, 2, 3])


In [33]:
y+=1
print(y) #y是x的索引出来的向量
print(x[0,:])

tensor([5, 6, 7])
tensor([5, 6, 7])


In [34]:
# 原来x的维度是5*3
y=x.view(15)
z=x.view(-1,5)  #-1所指的维度可以根据其他维度的值推出来。例如指定第二维是5，那么计算得到第一维是3
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)**

In [35]:
x+=1
print(x)
print(y)

tensor([[ 6,  7,  8],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13],
        [14, 15, 16]])
tensor([ 6,  7,  8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


> 这里非常重要！经常会使用

所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是**其拷贝**，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。

In [36]:
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[ 5,  6,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([ 6,  7,  8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


> 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

item()函数可以将tensor里面的数拿出来

In [37]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.2080])
-0.20800696313381195


## 广播机制
对两个形状不同的tensor做运算时可能会触发广播机制，所以内部会适当复制元素让这两个tensor的形状相同，再按元素进行运算。

In [5]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


1行2列+3行1列，对于第一列，x一行，y三行，所以一行的复制三次，变成三行，加上去；第二列同理复制三次加上去，变成345。
## Tensor和numpy的相互转换

我们很容易用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是： **这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**

In [3]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)


tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


numpy转tensor

In [4]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [6]:
a+=1
print(a,b) #可以看出来还是共享内存的
b+=1
print(a,b)


[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


不共享内存的方法！使用torch.tensor

In [7]:
c=torch.tensor(a)
a+=1
print(a,c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


tensor格式可以在gpu也可以在cpu上
可以相互转换移动

In [8]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


# 自动求梯度

Tensor是这个包的核心类，如果将其属性.requires_grad设置为True，它将开始追踪(track)在其上的所有操作（这样就可以利用链式法则进行梯度传播了）。完成计算后，可以调用.backward()来完成所有梯度计算。此Tensor的梯度将累积到.grad属性中。

注意在y.backward()时，如果y是标量，则不需要为backward()传入任何参数；否则，需要传入一个与y同形的Tensor。解释见 2.3.2 节。

如果不想要被继续追踪，可以调用.detach()将其从追踪记录中分离出来，这样就可以防止将来的计算被追踪，这样梯度就传不过去了。此外，还可以用with torch.no_grad()将不想被追踪的操作代码块包裹起来，这种方法在评估模型的时候很常用，因为在评估模型时，我们并不需要计算可训练参数（requires_grad=True）的梯度。

Function是另外一个很重要的类。Tensor和Function互相结合就可以构建一个记录有整个计算过程的有向无环图（DAG）。每个Tensor都有一个.grad_fn属性，该属性即创建该Tensor的Function, 就是说该Tensor是不是通过某些运算得到的，若是，则grad_fn返回一个与这些运算相关的对象，否则是None。

下面通过一些例子来理解这些概念。

## Tensor
创建Tensor，设置requires_grads=True

In [10]:
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [12]:
y=x+2
print(y)    #索引会共享内存，但是赋值不会
print(x)
print(y.grad_fn)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


x是直接创造的座椅他没有grad，而y是通过加法创造的，所以有一个Add的grad_fn

In [13]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


通过.requires_grad_()来用in-place的方式改变requires_grad属性：

In [14]:
a = torch.randn(2, 2) # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度
因为out是一个标量，所以调用backward()时不需要指定求导变量：

In [15]:
out.backward() # 等价于 out.backward(torch.tensor(1.))反向求导

我们来看看out关于x的梯度$\frac{d(out)}{dx}$

In [16]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


[详细的推导，看原文](https://tangshusen.me/Dive-into-DL-PyTorch/#/chapter02_prerequisite/2.3_autograd)

grad在反向传播过程中是累加的(accumulated)，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。

In [19]:
#再次反向传播，grad累加
out2=x.sum()
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


可见结果累加了，4.5-5.5

In [20]:
out3=x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


结果发现恢复
所谓标量就是一个数，张量就是tensor格式的向量

现在我们解释2.3.1节留下的问题，为什么在y.backward()时，如果y是标量，则不需要为backward()传入任何参数；否则，需要传入一个与y同形的Tensor? 简单来说就是为了避免向量（甚至更高维张量）对张量求导，而转换成标量对张量求导。举个例子，假设形状为 m x n 的矩阵 X 经过运算得到了 p x q 的矩阵 Y，Y 又经过运算得到了 s x t 的矩阵 Z。那么按照前面讲的规则，dZ/dY 应该是一个 s x t x p x q 四维张量，dY/dX 是一个 p x q x m x n的四维张量。问题来了，怎样反向传播？怎样将两个四维张量相乘？？？这要怎么乘？？？就算能解决两个四维张量怎么乘的问题，四维和三维的张量又怎么乘？导数的导数又怎么求，这一连串的问题，感觉要疯掉…… 为了避免这个问题，我们不允许张量对张量求导，只允许标量对张量求导，求导结果是和自变量同形的张量。所以必要时我们要把张量通过将所有张量的元素加权求和的方式转换为标量，举个例子，假设y由自变量x计算而来，w是和y同形的张量，则y.backward(w)的含义是：先计算l = torch.sum(y * w)，则l是个标量，然后求l对自变量x的导数

In [21]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True


True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [22]:
y3.backward()
print(x.grad)

tensor(2.)


可以看到结果是2.但是$y_3=y_1+y_2=x^2+x^3,$当$x=1$的时候，$\frac{d_{y_3}}{d_x}$应该是5，但是由于`with torch.no_grad()`包裹的部分，所以y2的梯度不会回传，只有y1会回传。

In [23]:
y2.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn